site_name: "Poro Language Space"
nav:
  - Trang Chủ: index.md
  - Tài Liệu:
      - ICS: ics.md
      - Buddy: Buddy.md
      - App Sakumi: appsakumi.md
      - App Đắc Nhân: appdacnhan.md
      - Test Plan: testplan.md
theme:
  name: material
  font:
    text: Inter
    code: Fira Code
  logo: assets/images/pls-logo.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - header.autohide
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Chế độ sáng (Light mode)
      primary: indigo
      accent: blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Chế độ tối (Dark mode)
      primary: indigo
      accent: blue
extra_css:
  - styles/extra.css
  - styles/home.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - toc:
      permalink: false
      toc_depth: 5
extra:
  admonition:
    icons:
      info: material/book-open-variant
extra_javascript:
  - scripts/open-toc-book.js
  - scripts/serinus-layout.js
  - scripts/home.js
  - scripts/animations.js
